[problem]
name = "OoC_Grid_Problem"
neq = 4
problem_type = "ooc"

[time_parameters]
T = 1.0
dt = 0.1

[discretization]
n_elements = 10
tau = [ 0.5, 0.5, 0.5, 0.5,]

[initial_conditions]
u = "zeros"
omega = "zeros"
v = "zeros"
phi = "zeros"

[force_functions]
u = "zeros"
omega = "zeros"
v = "zeros"
phi = "zeros"

[domain_initial_conditions]
domain_0_v = "constant"
domain_3_u = "constant"

[domain_force_functions]

[physical_parameters.viscosity]
nu = 200.0
mu = 850.0
epsilon = 600.0
sigma = 200.0

[physical_parameters.reaction]
a = 9.999999999999999e-6
c = 0.0001

[physical_parameters.coupling]
b = 9.999999999999999e-6
d = 0.0001
chi = 50.0
